export const ANIMATION = {
  BASE_DELAY: 450,
  STAGGER_INCREMENT: 150,
  FAST_INCREMENT: 80,
  MEDIUM_INCREMENT: 100,
  SLOW_INCREMENT: 120,
  HEADER_DURATION: 800,
  FADE_DURATION: 300,
  RANK_DURATION: 1000,

  LEGEND_BASE_DELAY: 600,
  LEGEND_INCREMENT: 50,
  PROFILE_BASE_DELAY: 250,
  CHART_BASE_DELAY: 350,
  CHART_INCREMENT: 70,
} as const;

export const SPACING = {
  CARD_PADDING: 25,
  HEADER_Y: 35,
  CONTENT_Y: 55,
  ROW_HEIGHT: 25,
  ROW_HEIGHT_COMPACT: 22,
  ROW_HEIGHT_LARGE: 26,
  SECTION_GAP: 30,
  ITEM_GAP: 18,
  BAR_SPACING: 42,
} as const;

export const TYPOGRAPHY = {
  HEADER_SIZE: 18,
  HEADER_SIZE_LARGE: 20,
  TITLE_HORIZONTAL_PADDING: 40,
  TITLE_INITIAL_FONT_SIZE: 18,
  KPI_SIZE: 24,
  STAT_SIZE: 13,
  STAT_LABEL_SIZE: 12,
  STAT_VALUE_SIZE: 14,
  SECTION_TITLE_SIZE: 11,
  SMALL_TEXT_SIZE: 10,
  LARGE_TEXT_SIZE: 16,
  USERNAME_SIZE: 18,
  MIN_FONT_SIZE: 8,
} as const;

export const MIN_FONT_SIZE = TYPOGRAPHY.MIN_FONT_SIZE;

export const SHAPES = {
  CIRCLE_RADIUS_LARGE: 40,
  CIRCLE_RADIUS_MEDIUM: 30,
  CIRCLE_RADIUS_SMALL: 28,
  CIRCLE_STROKE_WIDTH: 6,
  CIRCLE_STROKE_WIDTH_THIN: 5,
  AVATAR_RADIUS: 30,
  BAR_HEIGHT: 14,
  BAR_HEIGHT_SMALL: 10,
  BAR_HEIGHT_LARGE: 16,
  BAR_RADIUS: 3,
  CELL_SIZE: 10,
  CELL_GAP: 2,
} as const;

export const POSITIONING = {
  STAT_LABEL_X: 0,
  // Default value-column X offset used by the shared media stats layouts; the
  // fractional .01 keeps the default alignment stable while callers can still
  // override spacing for variant-specific layouts.
  STAT_VALUE_X_DEFAULT: 199.01,
  STAT_VALUE_X_COMPACT: 160,
  STAT_VALUE_X_SMALL: 120,
  STAT_VALUE_X_LARGE: 125,
  VALUE_MAX_WIDTH_VERTICAL: 45,
  VALUE_MAX_WIDTH_COMPACT: 56,
  VALUE_MAX_WIDTH_DEFAULT: 110,
  BAR_START_X: 30,
  BAR_START_X_LARGE: 150,
  COUNT_BASE_X: 35,
  RIGHT_PADDING: 60,
  AVATAR_OFFSET_X: 100,
} as const;

// Common default gap for row-fit and milestone-style layouts. Individual
// templates may still override this when their spacing needs diverge.
export const DEFAULT_GAP_PX = 12;

export const MILESTONES = {
  BAR_SPACING: 42,
  BAR_HEIGHT: 14,
  ROW_Y_OFFSET: -22,
  ROW_HEIGHT: 34,
  LABEL_Y_OFFSET: -8,
  VALUE_Y_OFFSET: -3,
  GAP_PX: DEFAULT_GAP_PX,
  SECONDARY_WIDTH_RATIO: 0.38,
  VALUE_MAX_WIDTH: 48,
  HORIZONTAL_PADDING: 24,
  BASE_DELAY: 400,
  DELAY_INCREMENT: 100,
} as const;

export const ROW_FIT = {
  GAP_PX: DEFAULT_GAP_PX,
  SECONDARY_MAX_WIDTH: 96,
  MIN_FONT_SIZE,
} as const;

export const ACTIVITY_STREAK = {
  GAP_PX: DEFAULT_GAP_PX,
  SECONDARY_MAX_WIDTH_BASE: 64,
  SECONDARY_MAX_WIDTH_RATIO: 0.42,
} as const;

export const CARD_HORIZONTAL_PADDING = 40;

export const DISTRIBUTION = {
  MAX_BAR_WIDTH_OFFSET: 60,
  COUNT_BASE_X: 35,
  BAR_START_X: 30,
  VERTICAL_BAR_WIDTH: 12,
  VERTICAL_BAR_SPACING: 28,
  VERTICAL_BAR_MAX_HEIGHT: 70,
  VERTICAL_BAR_Y_BASE: 90,
  MAX_ITEMS: 15,
} as const;

export const PROFILE = {
  AVATAR_SIZE: 60,
  AVATAR_RADIUS: 30,
  AVATAR_STROKE_WIDTH: 2,
  SECTION_SPACING: 150,
  YEARS_SECTION_X: 300,
  USERNAME_OFFSET: 120,
} as const;
