// app/layout.tsx
//
// Composes the shared shell for every route: fonts, structured data,
// thin analytics bootstrap, and the global layout wrapper.
//
// The early accessibility script runs before React hydrates so skip-link and
// mobile-menu interactions still work during slow boots or while JavaScript is loading.

import "./globals.css";

import type { Metadata, Viewport } from "next";
import {
  Geist,
  Geist_Mono,
  Libre_Baskerville,
  Playfair_Display_SC,
} from "next/font/google";
import { Suspense } from "react";

import AnalyticsBootstrap from "@/components/AnalyticsProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import GithubCorner from "@/components/GithubCorner";
import { LayoutShell } from "@/components/LayoutShell";
import ResourceHints from "@/components/ResourceHints";
import SkipLink from "@/components/SkipLink";
import { StructuredDataScript } from "@/components/StructuredDataScript";
import { getRequestNonce } from "@/lib/request-nonce";
import { siteMetadata } from "@/lib/seo";
import { buildEarlyAccessibilityShellScript } from "@/lib/shell-a11y";
import { generateSiteStructuredData } from "@/lib/structured-data";

import { Providers } from "./providers";

// Inline because the skip link and mobile-menu fallback need to work before any
// client component can attach event handlers.
const EARLY_ACCESSIBILITY_SHELL_SCRIPT = buildEarlyAccessibilityShellScript();

/**
 * Maps the Geist Sans face to the global CSS variable for site typography.
 * @source
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Exposes the Geist Mono face via a CSS variable for monospaced UI elements.
 * @source
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplaySC = Playfair_Display_SC({
  variable: "--font-playfair-display-sc",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = siteMetadata;

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  colorScheme: "light dark",
};

/**
 * Root layout that injects fonts, analytics, and the shared shell.
 *
 * This layout also integrates Content Security Policy (CSP) support by:
 * - Retrieving the nonce from request headers (generated by middleware)
 * - Passing the nonce to GoogleAnalytics for its inline scripts
 *
 * @param children - Page content rendered within the shared layout and providers.
 * @see app/middleware.ts for CSP header generation
 * @see lib/csp-config.ts for CSP directive configuration
 * @see docs/PRIVACY.md for the current analytics consent and telemetry posture
 * @source
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = await getRequestNonce();
  const isVercelDeployment = process.env.VERCEL === "1";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ResourceHints />
      </head>
      <body
        id="app-root"
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplaySC.variable} ${libreBaskerville.variable}
          antialiased
        `}
      >
        <SkipLink />
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: EARLY_ACCESSIBILITY_SHELL_SCRIPT,
          }}
        />
        <GithubCorner />
        <StructuredDataScript
          data={generateSiteStructuredData()}
          nonce={nonce}
        />
        <Suspense fallback={null}>
          <AnalyticsBootstrap
            enableRuntimeTelemetry={isVercelDeployment}
            trackingId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
            nonce={nonce}
          />
        </Suspense>
        <Providers nonce={nonce}>
          <ErrorBoundary>
            <LayoutShell>{children}</LayoutShell>
          </ErrorBoundary>
        </Providers>
      </body>
    </html>
  );
}
