import "./globals.css";

import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Libre_Baskerville,
  Playfair_Display_SC,
} from "next/font/google";
import { headers } from "next/headers";
import { Suspense } from "react";

import AnalyticsProvider from "@/components/AnalyticsProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import GithubCorner from "@/components/GithubCorner";
import { LayoutShell } from "@/components/LayoutShell";
import { StructuredDataScript } from "@/components/StructuredDataScript";
import { getDefaultSocialPreviewImages } from "@/lib/seo";
import { getSiteUrlObject } from "@/lib/site-config";
import { generateSiteStructuredData } from "@/lib/structured-data";

import { Providers } from "./providers";

/**
 * Maps the Geist Sans face to the global CSS variable for site typography.
 * @source
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Exposes the Geist Mono face via a CSS variable for monospaced UI elements.
 * @source
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplaySC = Playfair_Display_SC({
  variable: "--font-playfair-display-sc",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  metadataBase: getSiteUrlObject(),
  openGraph: {
    images: getDefaultSocialPreviewImages(),
  },
  twitter: {
    card: "summary_large_image",
    images: getDefaultSocialPreviewImages(),
  },
};

/**
 * Root layout that injects fonts, analytics, and the shared shell.
 *
 * This layout also integrates Content Security Policy (CSP) support by:
 * - Retrieving the nonce from request headers (generated by middleware)
 * - Passing the nonce to GoogleAnalytics for its inline scripts
 *
 * @param children - Page content rendered within the shared layout and providers.
 * @see app/middleware.ts for CSP header generation
 * @see lib/csp-config.ts for CSP directive configuration
 * @source
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const nonce = headersList.get("x-nonce") || undefined;
  const isVercelDeployment = process.env.VERCEL === "1";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        id="app-root"
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplaySC.variable} ${libreBaskerville.variable}
          antialiased
        `}
      >
        <GithubCorner />
        <Providers>
          <Suspense fallback={<div>Loading...</div>}>
            <StructuredDataScript data={generateSiteStructuredData()} />
            <AnalyticsProvider
              enableRuntimeTelemetry={isVercelDeployment}
              trackingId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
              nonce={nonce}
            >
              <ErrorBoundary>
                <LayoutShell>{children}</LayoutShell>
              </ErrorBoundary>
            </AnalyticsProvider>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
