import "./globals.css";

import type { Metadata, Viewport } from "next";
import {
  Geist,
  Geist_Mono,
  Libre_Baskerville,
  Playfair_Display_SC,
} from "next/font/google";
import { Suspense } from "react";

import AnalyticsProvider from "@/components/AnalyticsProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import GithubCorner from "@/components/GithubCorner";
import { LayoutShell } from "@/components/LayoutShell";
import PwaRegistration from "@/components/PwaRegistration";
import { StructuredDataScript } from "@/components/StructuredDataScript";
import { getRequestNonce } from "@/lib/request-nonce";
import { getDefaultSocialPreviewImages } from "@/lib/seo";
import { getSiteUrlObject, SITE_NAME } from "@/lib/site-config";
import { generateSiteStructuredData } from "@/lib/structured-data";

import { Providers } from "./providers";

const LIGHT_THEME_COLOR = "#faf6f0";
const DARK_THEME_COLOR = "#0c0a10";

/**
 * Maps the Geist Sans face to the global CSS variable for site typography.
 * @source
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Exposes the Geist Mono face via a CSS variable for monospaced UI elements.
 * @source
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplaySC = Playfair_Display_SC({
  variable: "--font-playfair-display-sc",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  metadataBase: getSiteUrlObject(),
  applicationName: SITE_NAME,
  manifest: "/manifest.webmanifest",
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: SITE_NAME,
  },
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        sizes: "any",
      },
      {
        url: "/pwa/icon-any.svg",
        type: "image/svg+xml",
      },
    ],
    shortcut: ["/favicon.ico"],
    apple: [
      {
        url: "/pwa/apple-touch-icon.svg",
        sizes: "180x180",
        type: "image/svg+xml",
      },
    ],
  },
  openGraph: {
    images: getDefaultSocialPreviewImages(),
  },
  twitter: {
    card: "summary_large_image",
    images: getDefaultSocialPreviewImages(),
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  colorScheme: "light dark",
  themeColor: [
    {
      media: "(prefers-color-scheme: light)",
      color: LIGHT_THEME_COLOR,
    },
    {
      media: "(prefers-color-scheme: dark)",
      color: DARK_THEME_COLOR,
    },
  ],
};

/**
 * Root layout that injects fonts, analytics, and the shared shell.
 *
 * This layout also integrates Content Security Policy (CSP) support by:
 * - Retrieving the nonce from request headers (generated by middleware)
 * - Passing the nonce to GoogleAnalytics for its inline scripts
 *
 * @param children - Page content rendered within the shared layout and providers.
 * @see app/middleware.ts for CSP header generation
 * @see lib/csp-config.ts for CSP directive configuration
 * @see docs/PRIVACY.md for the current analytics consent and telemetry posture
 * @source
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = await getRequestNonce();
  const isVercelDeployment = process.env.VERCEL === "1";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        id="app-root"
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplaySC.variable} ${libreBaskerville.variable}
          antialiased
        `}
      >
        <GithubCorner />
        <Providers>
          <PwaRegistration />
          <Suspense fallback={<div>Loading...</div>}>
            <StructuredDataScript
              data={generateSiteStructuredData()}
              nonce={nonce}
            />
            <AnalyticsProvider
              enableRuntimeTelemetry={isVercelDeployment}
              trackingId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
              nonce={nonce}
            >
              <ErrorBoundary>
                <LayoutShell>{children}</LayoutShell>
              </ErrorBoundary>
            </AnalyticsProvider>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
