import { headers } from "next/headers";

/**
 * Reads the per-request CSP nonce from the forwarded request headers.
 *
 * @returns The nonce generated by middleware, or undefined when the request
 *          is rendered outside the document/HTML pipeline.
 * @source
 */
export async function getRequestNonce(): Promise<string | undefined> {
  return (await headers()).get("x-nonce") || undefined;
}
